apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    autopilot.gke.io/resource-adjustment: '{"input":{"containers":[{"name":"w6-demo-sha256-1"}]},"output":{"containers":[{"limits":{"ephemeral-storage":"1Gi"},"requests":{"cpu":"500m","ephemeral-storage":"1Gi","memory":"2Gi"},"name":"w6-demo-sha256-1"}]},"computeClassAtAdmission":"Default","modified":true}'
    autopilot.gke.io/warden-version: 33.26.0-gke.2
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"autopilot.gke.io/resource-adjustment":"{\"input\":{\"containers\":[{\"name\":\"w6-demo-sha256-1\"}]},\"output\":{\"containers\":[{\"limits\":{\"ephemeral-storage\":\"1Gi\"},\"requests\":{\"cpu\":\"500m\",\"ephemeral-storage\":\"1Gi\",\"memory\":\"2Gi\"},\"name\":\"w6-demo-sha256-1\"}]},\"computeClassAtAdmission\":\"Default\",\"modified\":true}","autopilot.gke.io/warden-version":"33.26.0-gke.2","deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2025-07-27T15:00:40Z","generation":3,"labels":{"app":"week6-wl","app.kubernetes.io/managed-by":"cloud-console"},"name":"week6-wl","namespace":"default","resourceVersion":"1753628936479087008","uid":"3c52a912-60ef-491a-9893-643d0c11480c"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"week6-wl","app.kubernetes.io/managed-by":"cloud-console"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"week6-wl","app.kubernetes.io/managed-by":"cloud-console"}},"spec":{"containers":[{"image":"us-central1-docker.pkg.dev/arboreal-harbor-461417-u1/w6-mlops/w6-demo@sha256:a8683e3253bf143e853a0d9208588aa8088cada4c995dce85fa9cd1cb7528e11","imagePullPolicy":"IfNotPresent","name":"w6-demo-sha256-1","resources":{"limits":{"ephemeral-storage":"1Gi"},"requests":{"cpu":"500m","ephemeral-storage":"1Gi","memory":"2Gi"}},"securityContext":{"capabilities":{"drop":["NET_RAW"]}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{"seccompProfile":{"type":"RuntimeDefault"}},"terminationGracePeriodSeconds":30,"tolerations":[{"effect":"NoSchedule","key":"kubernetes.io/arch","operator":"Equal","value":"amd64"}]}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2025-07-27T15:03:10Z","lastUpdateTime":"2025-07-27T15:03:10Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2025-07-27T15:00:40Z","lastUpdateTime":"2025-07-27T15:03:10Z","message":"ReplicaSet \"week6-wl-57b66d595f\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":3,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  
  generation: 4
  labels:
    app: week6-wl
    app.kubernetes.io/managed-by: cloud-console
  name: week6-wl
  namespace: default
  
  
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: week6-wl
      app.kubernetes.io/managed-by: cloud-console
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: week6-wl
        app.kubernetes.io/managed-by: cloud-console
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/arboreal-harbor-461417-u1/w6-mlops/w6-demo@sha256:a8683e3253bf143e853a0d9208588aa8088cada4c995dce85fa9cd1cb7528e11
        imagePullPolicy: IfNotPresent
        name: w6-demo-sha256-1
        resources:
          limits:
            ephemeral-storage: 1Gi
          requests:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
        securityContext:
          capabilities:
            drop:
            - NET_RAW
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: kubernetes.io/arch
        operator: Equal
        value: amd64
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-07-27T15:00:40Z"
    lastUpdateTime: "2025-07-27T16:08:22Z"
    message: ReplicaSet "week6-wl-cd5c6cbdc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-07-27T16:09:46Z"
    lastUpdateTime: "2025-07-27T16:09:46Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
