name: Build and Deploy Iris API to GKE

on:
  push:
    branches: [ "main" ]

# Environment variables available to all jobs and steps
env:
  GCP_PROJECT_ID: arboreal-harbor-461417-u1
  GKE_CLUSTER: mlops-cluster-1
  GKE_REGION: us-central1
  ARTIFACT_REGISTRY: us-central1-docker.pkg.dev
  REPO_NAME: w6-mlops
  IMAGE_NAME: w6-demo
  # MODEL_BUCKET_URI: gs://mlops-course-mlopsweek1-unique/my-models/iris-classifier-week-1/model.joblib

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 20 # Prevent runaway jobs

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Authenticate to GCP
      id: 'auth' # Assign an ID to this step to refer to its outputs if needed
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Run training file
      run: |
        echo "Running The training file"
        # gcloud storage cp "${{ env.MODEL_BUCKET_URI }}" ./api/model.joblib
        pip install -r requirements.txt
        python train.py
        echo "Model.joblib saved"

    - name: Set up GKE credentials
      run: |
        echo "Configuring kubectl for GKE cluster..."
        gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --region ${{ env.GKE_REGION }} --project ${{ env.GCP_PROJECT_ID }}
        echo "GKE credentials configured."

    - name: Install gke-gcloud-auth-plugin
      run: |
        echo "Setting up Google Cloud APT repository..."
        sudo apt-get update
        sudo apt-get install -y apt-transport-https ca-certificates gnupg curl
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
        
        echo "Installing gke-gcloud-auth-plugin..."
        sudo apt-get update
        sudo apt-get install -y google-cloud-cli-gke-gcloud-auth-plugin
        echo "gke-gcloud-auth-plugin installed."

    - name: Configure Docker for Artifact Registry
      run: |
        echo "Configuring Docker for Artifact Registry..."
        gcloud auth configure-docker ${{ env.ARTIFACT_REGISTRY }}
        echo "Docker configured."

    - name: Build and Push Docker Image
      run: |
        echo "🔨 Building Docker image..."
        IMAGE_TAG_SHA="${{ env.ARTIFACT_REGISTRY }}/${{ env.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
        IMAGE_TAG_LATEST="${{ env.ARTIFACT_REGISTRY }}/${{ env.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:latest"
        
        docker build -t "$IMAGE_TAG_SHA" -t "$IMAGE_TAG_LATEST" .
        
        echo "Pushing Docker images..."
        docker push "$IMAGE_TAG_SHA"
        docker push "$IMAGE_TAG_LATEST"
        
        echo "Docker images built and pushed."
        echo "IMAGE_TAG_SHA=$IMAGE_TAG_SHA" >> $GITHUB_ENV

    - name: Deploy to GKE
      run: |
        echo "Deploying to GKE..."
        sed -i "s|image: .*|image: ${{ env.IMAGE_TAG_SHA }}|g" deployment-file.yaml
        
        echo "Applying updated deployment-file.yaml:"
        cat deployment-file.yaml
        
        kubectl apply -f deployment-file.yaml
        
        # echo "Waiting for deployment rollout to complete..."
        # kubectl rollout status Deployment/week6-demo-Deployment --timeout=300s
        # echo "Deployment completed successfully."
